import Link from 'next/link'
import { Badge } from '@/components/ui/badge'
import { Card } from '@/components/ui/card'

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center space-x-2">
              <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
                <span className="text-primary-foreground font-bold text-sm">P</span>
              </div>
              <h1 className="text-xl font-semibold">bestmate</h1>
            </Link>
            <Badge variant="secondary" className="text-xs">
              Beta
            </Badge>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-6 py-12 max-w-4xl">
        <div className="space-y-8">
          {/* Header */}
          <div className="text-center space-y-4">
            <h1 className="text-4xl font-bold">Privacy Policy</h1>
            <p className="text-lg text-muted-foreground">
              Last updated: {new Date().toLocaleDateString()}
            </p>
            <p className="text-sm text-muted-foreground">
              We take your privacy seriously. This policy explains how we collect, use, and protect your data.
            </p>
          </div>

          {/* Table of Contents */}
          <Card className="p-6">
            <h2 className="text-xl font-semibold mb-4">Table of Contents</h2>
            <ul className="space-y-2 text-sm">
              <li><a href="#information-we-collect" className="text-primary hover:underline">1. Information We Collect</a></li>
              <li><a href="#how-we-use" className="text-primary hover:underline">2. How We Use Your Information</a></li>
              <li><a href="#data-storage" className="text-primary hover:underline">3. Data Storage and Security</a></li>
              <li><a href="#cookies" className="text-primary hover:underline">4. Cookies and Tracking</a></li>
              <li><a href="#third-party" className="text-primary hover:underline">5. Third-Party Services</a></li>
              <li><a href="#your-rights" className="text-primary hover:underline">6. Your Rights</a></li>
              <li><a href="#data" className="text-primary hover:underline">7. Data Retention</a></li>
              <li><a href="#contact" className="text-primary hover:underline">8. Contact Us</a></li>
            </ul>
          </Card>

          {/* Content Sections */}
          <div className="space-y-8">
            <section id="information-we-collect">
              <h2 className="text-2xl font-semibold mb-4">1. Information We Collect</h2>
              <div className="prose prose-gray max-w-none">
                <h3 className="text-lg font-medium mb-2">Personal Information</h3>
                <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                  <li>Email address (for account creation and authentication)</li>
                  <li>GitHub username (if you connect your GitHub account)</li>
                  <li>Usage data (prompts submitted, optimizations performed)</li>
                </ul>

                <h3 className="text-lg font-medium mb-2 mt-4">Prompt Data</h3>
                <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                  <li>Original prompts you submit for optimization</li>
                  <li>Optimized prompts generated by our system</li>
                  <li>Evaluation results and performance metrics</li>
                  <li>Test cases and benchmarks you create</li>
                </ul>

                <h3 className="text-lg font-medium mb-2 mt-4">Technical Data</h3>
                <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                  <li>IP address and browser information</li>
                  <li>Device type and operating system</li>
                  <li>Session data and usage patterns</li>
                  <li>Error logs and performance analytics</li>
                </ul>
              </div>
            </section>

            <section id="how-we-use">
              <h2 className="text-2xl font-semibold mb-4">2. How We Use Your Information</h2>
              <div className="prose prose-gray max-w-none">
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li><strong>Service Provision:</strong> To provide prompt optimization, evaluation, and insights</li>
                  <li><strong>Global Intelligence:</strong> To improve our vector database with anonymized prompt patterns</li>
                  <li><strong>Authentication:</strong> To manage your account and secure access</li>
                  <li><strong>Usage Tracking:</strong> To monitor daily token limits and prevent abuse</li>
                  <li><strong>Improvement:</strong> To enhance our algorithms and user experience</li>
                  <li><strong>Communication:</strong> To send important service updates and notifications</li>
                </ul>

                <div className="mt-4 p-4 bg-blue-50 dark:bg-blue-950 rounded-lg">
                  <p className="text-sm text-blue-800 dark:text-blue-200">
                    <strong>Global Prompt Pool:</strong> Your prompts may be added to our global knowledge base 
                    to help improve optimization for all users. All prompts are anonymized and stripped of 
                    identifying information before being added to the shared pool.
                  </p>
                </div>
              </div>
            </section>

            <section id="data-storage">
              <h2 className="text-2xl font-semibold mb-4">3. Data Storage and Security</h2>
              <div className="prose prose-gray max-w-none">
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li><strong>Encryption:</strong> All data is encrypted in transit and at rest</li>
                  <li><strong>Supabase:</strong> User data is securely stored in Supabase with RLS policies</li>
                  <li><strong>Pinecone:</strong> Vector embeddings are stored in Pinecone for similarity search</li>
                  <li><strong>Access Control:</strong> Strict access controls limit who can view your data</li>
                  <li><strong>Regular Backups:</strong> Data is regularly backed up to prevent loss</li>
                  <li><strong>Monitoring:</strong> We monitor for security threats and unauthorized access</li>
                </ul>
              </div>
            </section>

            <section id="cookies">
              <h2 className="text-2xl font-semibold mb-4">4. Cookies and Tracking</h2>
              <div className="prose prose-gray max-w-none">
                <p className="text-muted-foreground mb-4">
                  We use cookies and similar technologies to enhance your experience:
                </p>
                <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                  <li><strong>Essential Cookies:</strong> Required for authentication and basic functionality</li>
                  <li><strong>Session Cookies:</strong> To maintain your login state across pages</li>
                  <li><strong>Preference Cookies:</strong> To remember your settings and preferences</li>
                  <li><strong>Analytics:</strong> To understand how you use our service (anonymized)</li>
                </ul>
                <p className="text-sm text-muted-foreground mt-4">
                  You can control cookies through your browser settings, but disabling them may affect functionality.
                </p>
              </div>
            </section>

            <section id="third-party">
              <h2 className="text-2xl font-semibold mb-4">5. Third-Party Services</h2>
              <div className="prose prose-gray max-w-none">
                <p className="text-muted-foreground mb-4">
                  We use the following third-party services to provide our functionality:
                </p>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li><strong>Supabase:</strong> Database and authentication services</li>
                  <li><strong>Pinecone:</strong> Vector database for prompt similarity matching</li>
                  <li><strong>Google Gemini:</strong> AI model for embeddings and optimization</li>
                  <li><strong>GitHub:</strong> Repository integration (optional)</li>
                  <li><strong>Vercel:</strong> Hosting and deployment platform</li>
                </ul>
                <p className="text-sm text-muted-foreground mt-4">
                  Each service has its own privacy policy governing how they handle data.
                </p>
              </div>
            </section>

            <section id="your-rights">
              <h2 className="text-2xl font-semibold mb-4">6. Your Rights</h2>
              <div className="prose prose-gray max-w-none">
                <p className="text-muted-foreground mb-4">
                  You have the following rights regarding your personal data:
                </p>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li><strong>Access:</strong> Request a copy of your personal data</li>
                  <li><strong>Correction:</strong> Update or correct inaccurate information</li>
                  <li><strong>Deletion:</strong> Request deletion of your account and data</li>
                  <li><strong>Portability:</strong> Export your data in a machine-readable format</li>
                  <li><strong>Objection:</strong> Object to certain uses of your data</li>
                  <li><strong>Restriction:</strong> Request limitation of data processing</li>
                </ul>
                <p className="text-sm text-muted-foreground mt-4">
                  To exercise these rights, contact us at{' '}
                  <a href="mailto:kaya@forver22studios.com" className="text-primary hover:underline">
                    kaya@forver22studios.com
                  </a>
                </p>
              </div>
            </section>

            <section id="data">
              <h2 className="text-2xl font-semibold mb-4">7. Data Retention</h2>
              <div className="prose prose-gray max-w-none">
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li><strong>Account Data:</strong> Retained until you delete your account</li>
                  <li><strong>Prompt History:</strong> Stored for your reference and service improvement</li>
                  <li><strong>Analytics Data:</strong> Anonymized data may be retained indefinitely</li>
                  <li><strong>Global Prompt Pool:</strong> Anonymized prompts may be retained permanently</li>
                  <li><strong>Session Data:</strong> Automatically deleted after 30 days of inactivity</li>
                </ul>
              </div>
            </section>

            <section id="contact">
              <h2 className="text-2xl font-semibold mb-4">8. Contact Us</h2>
              <div className="prose prose-gray max-w-none">
                <p className="text-muted-foreground mb-4">
                  If you have questions about this privacy policy or our data practices, please contact us:
                </p>
                <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                  <li>
                    <strong>Email:</strong>{' '}
                    <a href="mailto:kaya@forver22studios.com" className="text-primary hover:underline">
                      kaya@forver22studios.com
                    </a>
                  </li>
                  <li>
                    <strong>Twitter:</strong>{' '}
                    <a href="https://twitter.com/kayacancode" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
                      @kayacancode
                    </a>
                  </li>
                </ul>
                <p className="text-sm text-muted-foreground mt-4">
                  We will respond to your inquiry within 30 days.
                </p>
              </div>
            </section>
          </div>

          {/* Footer */}
          <div className="text-center pt-8 border-t">
            <p className="text-sm text-muted-foreground">
              This privacy policy is effective as of {new Date().toLocaleDateString()} and may be updated periodically.
            </p>
            <Link href="/" className="text-primary hover:underline text-sm">
              ← Back to bestmate
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
} 